# Site settings
title: MarCoach
description: Supporting public and private education, schools and universities
keywords: Linux, IoT, GDPR
author: Marco
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://mqtt.marcoach.nl/" # the base hostname & protocol for your site

markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Amsterdam

defaults:
- scope:
    path: _posts
    type: posts
  values:
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    sectionid: docs
    seo:
      type: "WebPage"