# Site settings
title: MarCoach.nl
description: Supporting educators
baseurl: "/" # the subpath of your site, e.g. /blog
url: "lhttp://192.168.15.9:4081" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Marco Verleun
user_description: Unix, Linux, IoT, GDPR, Education
user_title: Educational support
email: marco@marcoach.nl
#twitter_username: lorem_ipsum
github_username:  mverleun
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
