# Site settings
title: MarCoach
email: marco@marcoach.nl
description: > # this means to ignore newlines until "baseurl:"
  Education support and training for Linux, OS X, IoT and GDPR.
baseurl: "/" # the subpath of your site, e.g. /blog/
#url: "http://192.168.15.9:4081/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mverleun

# Build settings
markdown: kramdown
